CREATE TABLE sparkle_journal (
    journalId INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userId INTEGER REFERENCES sparkle_users(userId),
    journalTitle TEXT, 
    entryCount INTEGER
);