CREATE TABLE sparkle_journal (
    journalId INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userId uuid REFERENCES sparkle_users,
    journalTitle TEXT, 
    entryCount INTEGER
);

CREATE OR REPLACE FUNCTION add_journal()
    RETURNS trigger AS
$Body$
BEGIN
    INSERT INTO sparkle_journal(userId)
    VALUES(NEW.userId);

    RETURN NEW;
END;
$Body$
LANGUAGE 'plpgsql';

CREATE TRIGGER new_journal
  AFTER INSERT
  ON sparkle_users
  FOR EACH ROW
  EXECUTE PROCEDURE add_journal();